/**
 * Registry of 100+ crypto/web3 companies with their ATS platform & slugs.
 *
 * Greenhouse public API:
 *   GET https://boards-api.greenhouse.io/v1/boards/{atsSlug}/jobs?content=true
 *
 * Lever public API:
 *   GET https://api.lever.co/v0/postings/{atsSlug}?mode=json
 *
 * Ashby public API:
 *   GET https://api.ashbyhq.com/posting-api/job-board/{atsSlug}
 *
 * 404s are silently skipped at ingest time — slugs may drift as companies
 * switch ATS platforms; mark `active: false` to pause without deleting.
 */

export type ATSType = "greenhouse" | "lever" | "ashby" | "workable";

export interface CompanyEntry {
  name: string;
  slug: string; // Chainwork DB slug
  website: string;
  atsType: ATSType;
  atsSlug: string; // Slug used in ATS API URL
  ecosystems: string[]; // Known ecosystems (used as fallback tag)
  stage?: string;
  hq?: string;
  focus?: string; // one-liner description
  logoText: string; // 2-char monogram
  logoBg: string; // hex background
  logoFg: string; // hex foreground
  active?: boolean; // set false to pause without deleting
}

/* ── Greenhouse companies ──────────────────────────────────── */

const GREENHOUSE: CompanyEntry[] = [
  {
    name: "Coinbase",
    slug: "coinbase",
    website: "https://coinbase.com",
    atsType: "greenhouse",
    atsSlug: "coinbase",
    ecosystems: ["evm", "base"],
    stage: "Public",
    hq: "Remote-first (US)",
    focus: "The leading US crypto exchange and Base L2 builder",
    logoText: "CB",
    logoBg: "#0052FF",
    logoFg: "#FFFFFF",
  },
  {
    name: "Chainalysis",
    slug: "chainalysis",
    website: "https://chainalysis.com",
    atsType: "greenhouse",
    atsSlug: "chainalysis",
    ecosystems: ["evm", "bitcoin"],
    stage: "Series F",
    hq: "New York, NY",
    focus: "Blockchain analytics and compliance for crypto",
    logoText: "CA",
    logoBg: "#4ECDC4",
    logoFg: "#FFFFFF",
  },
  {
    name: "Gemini",
    slug: "gemini",
    website: "https://gemini.com",
    atsType: "greenhouse",
    atsSlug: "gemini",
    ecosystems: ["evm", "bitcoin"],
    stage: "Private",
    hq: "New York, NY",
    focus: "Regulated crypto exchange and custodian",
    logoText: "GE",
    logoBg: "#00DCFA",
    logoFg: "#000000",
  },
  {
    name: "Kraken",
    slug: "kraken",
    website: "https://kraken.com",
    atsType: "greenhouse",
    atsSlug: "kraken",
    ecosystems: ["evm", "bitcoin"],
    stage: "Private",
    hq: "Remote-first",
    focus: "Global crypto exchange with deep liquidity",
    logoText: "KR",
    logoBg: "#5741D9",
    logoFg: "#FFFFFF",
  },
  {
    name: "Paxos",
    slug: "paxos",
    website: "https://paxos.com",
    atsType: "greenhouse",
    atsSlug: "paxos",
    ecosystems: ["evm"],
    stage: "Series D",
    hq: "New York, NY",
    focus: "Regulated blockchain infrastructure for tokenized assets",
    logoText: "PX",
    logoBg: "#00C805",
    logoFg: "#000000",
  },
  {
    name: "Fireblocks",
    slug: "fireblocks",
    website: "https://fireblocks.com",
    atsType: "greenhouse",
    atsSlug: "fireblocks",
    ecosystems: ["evm", "bitcoin", "solana"],
    stage: "Series E",
    hq: "New York, NY",
    focus: "Digital asset security and operations platform",
    logoText: "FB",
    logoBg: "#FF6B35",
    logoFg: "#FFFFFF",
  },
  {
    name: "Anchorage Digital",
    slug: "anchorage-digital",
    website: "https://anchorage.com",
    atsType: "greenhouse",
    atsSlug: "anchorage",
    ecosystems: ["evm", "bitcoin"],
    stage: "Series D",
    hq: "San Francisco, CA",
    focus: "Federally chartered digital asset bank",
    logoText: "AN",
    logoBg: "#0A0B0D",
    logoFg: "#F5F5F5",
  },
  {
    name: "BitGo",
    slug: "bitgo",
    website: "https://bitgo.com",
    atsType: "greenhouse",
    atsSlug: "bitgo",
    ecosystems: ["bitcoin", "evm"],
    stage: "Series C",
    hq: "Palo Alto, CA",
    focus: "Institutional-grade digital asset custody and trading",
    logoText: "BG",
    logoBg: "#F7931A",
    logoFg: "#FFFFFF",
  },
  {
    name: "Bitstamp",
    slug: "bitstamp",
    website: "https://bitstamp.net",
    atsType: "greenhouse",
    atsSlug: "bitstamp",
    ecosystems: ["bitcoin", "evm"],
    stage: "Acquired (Robinhood)",
    hq: "Luxembourg",
    focus: "Europe's oldest cryptocurrency exchange",
    logoText: "BS",
    logoBg: "#E91D2D",
    logoFg: "#FFFFFF",
  },
  {
    name: "Ripple",
    slug: "ripple",
    website: "https://ripple.com",
    atsType: "greenhouse",
    atsSlug: "ripple",
    ecosystems: ["evm"],
    stage: "Private",
    hq: "San Francisco, CA",
    focus: "Blockchain-based global payments and CBDC infrastructure",
    logoText: "RP",
    logoBg: "#00AAE4",
    logoFg: "#FFFFFF",
  },
  {
    name: "OpenSea",
    slug: "opensea",
    website: "https://opensea.io",
    atsType: "greenhouse",
    atsSlug: "opensea",
    ecosystems: ["evm", "solana"],
    stage: "Series C",
    hq: "New York, NY",
    focus: "The world's largest NFT marketplace",
    logoText: "OS",
    logoBg: "#2081E2",
    logoFg: "#FFFFFF",
  },
  {
    name: "Alchemy",
    slug: "alchemy",
    website: "https://alchemy.com",
    atsType: "greenhouse",
    atsSlug: "alchemy",
    ecosystems: ["evm", "solana"],
    stage: "Series C",
    hq: "San Francisco, CA",
    focus: "The leading web3 developer platform and node infrastructure",
    logoText: "AL",
    logoBg: "#363FF9",
    logoFg: "#FFFFFF",
  },
  {
    name: "Figment",
    slug: "figment",
    website: "https://figment.io",
    atsType: "greenhouse",
    atsSlug: "figment",
    ecosystems: ["evm", "cosmos", "solana"],
    stage: "Series B",
    hq: "Toronto, Canada",
    focus: "Staking-as-a-service for institutional crypto investors",
    logoText: "FG",
    logoBg: "#7B3FE4",
    logoFg: "#FFFFFF",
  },
  {
    name: "dYdX",
    slug: "dydx",
    website: "https://dydx.exchange",
    atsType: "greenhouse",
    atsSlug: "dydx",
    ecosystems: ["evm", "cosmos"],
    stage: "Series D",
    hq: "Remote-first",
    focus: "Decentralized perpetuals DEX, migrated to Cosmos chain",
    logoText: "DX",
    logoBg: "#6966FF",
    logoFg: "#FFFFFF",
  },
  {
    name: "Immutable",
    slug: "immutable",
    website: "https://immutable.com",
    atsType: "greenhouse",
    atsSlug: "immutablex",
    ecosystems: ["evm", "polygon"],
    stage: "Series C",
    hq: "Sydney, Australia",
    focus: "Web3 gaming platform and zkEVM L2",
    logoText: "IM",
    logoBg: "#00E5BF",
    logoFg: "#000000",
  },
  {
    name: "Blockchain.com",
    slug: "blockchain-com",
    website: "https://blockchain.com",
    atsType: "greenhouse",
    atsSlug: "blockchaincom",
    ecosystems: ["bitcoin", "evm"],
    stage: "Series D",
    hq: "London, UK",
    focus: "Leading crypto wallet and exchange serving 80M+ users",
    logoText: "BC",
    logoBg: "#3D75C3",
    logoFg: "#FFFFFF",
  },
  {
    name: "Galaxy Digital",
    slug: "galaxy-digital",
    website: "https://galaxy.com",
    atsType: "greenhouse",
    atsSlug: "galaxydigitallp",
    ecosystems: ["evm", "bitcoin"],
    stage: "Public (GLXY)",
    hq: "New York, NY",
    focus: "Digital asset and blockchain financial services firm",
    logoText: "GD",
    logoBg: "#111827",
    logoFg: "#F9FAFB",
  },
  {
    name: "Nansen",
    slug: "nansen",
    website: "https://nansen.ai",
    atsType: "greenhouse",
    atsSlug: "nansen",
    ecosystems: ["evm", "solana"],
    stage: "Series B",
    hq: "Singapore",
    focus: "On-chain analytics platform with labeled wallet data",
    logoText: "NS",
    logoBg: "#FF5C35",
    logoFg: "#FFFFFF",
  },
  {
    name: "Messari",
    slug: "messari",
    website: "https://messari.io",
    atsType: "greenhouse",
    atsSlug: "messari",
    ecosystems: ["evm", "bitcoin"],
    stage: "Series B",
    hq: "New York, NY",
    focus: "Crypto market intelligence, research, and data",
    logoText: "MS",
    logoBg: "#1E40AF",
    logoFg: "#FFFFFF",
  },
  {
    name: "ConsenSys",
    slug: "consensys",
    website: "https://consensys.io",
    atsType: "greenhouse",
    atsSlug: "consensys",
    ecosystems: ["evm"],
    stage: "Series D",
    hq: "New York, NY",
    focus: "Ethereum software house behind MetaMask and Linea",
    logoText: "CN",
    logoBg: "#E37617",
    logoFg: "#FFFFFF",
  },
  {
    name: "Celo",
    slug: "celo-org",
    website: "https://celo.org",
    atsType: "greenhouse",
    atsSlug: "celo-org",
    ecosystems: ["evm"],
    stage: "Foundation",
    hq: "Remote-first",
    focus: "EVM L2 focused on mobile-first financial inclusion",
    logoText: "CE",
    logoBg: "#35D07F",
    logoFg: "#000000",
  },
  {
    name: "Offchain Labs (Arbitrum)",
    slug: "offchain-labs",
    website: "https://offchainlabs.com",
    atsType: "greenhouse",
    atsSlug: "offchain-labs",
    ecosystems: ["evm", "arbitrum"],
    stage: "Series B",
    hq: "New York, NY",
    focus: "Core developers behind Arbitrum rollup technology",
    logoText: "OL",
    logoBg: "#12AAFF",
    logoFg: "#000000",
  },
  {
    name: "BitPanda",
    slug: "bitpanda",
    website: "https://bitpanda.com",
    atsType: "greenhouse",
    atsSlug: "bitpanda",
    ecosystems: ["evm", "bitcoin"],
    stage: "Series C",
    hq: "Vienna, Austria",
    focus: "European retail crypto and asset investment platform",
    logoText: "BP",
    logoBg: "#00D97E",
    logoFg: "#000000",
  },
  {
    name: "Bitso",
    slug: "bitso",
    website: "https://bitso.com",
    atsType: "greenhouse",
    atsSlug: "bitso",
    ecosystems: ["evm", "bitcoin"],
    stage: "Series C",
    hq: "Mexico City, Mexico",
    focus: "Leading crypto exchange for Latin America",
    logoText: "BI",
    logoBg: "#00A651",
    logoFg: "#FFFFFF",
  },
  {
    name: "OKCoin",
    slug: "okcoin",
    website: "https://okcoin.com",
    atsType: "greenhouse",
    atsSlug: "okcoin",
    ecosystems: ["evm", "bitcoin"],
    stage: "Private",
    hq: "San Francisco, CA",
    focus: "Global crypto exchange serving retail and institutional traders",
    logoText: "OK",
    logoBg: "#101820",
    logoFg: "#F5F5F5",
  },
  {
    name: "Nexo",
    slug: "nexo",
    website: "https://nexo.com",
    atsType: "greenhouse",
    atsSlug: "nexo",
    ecosystems: ["evm", "bitcoin"],
    stage: "Private",
    hq: "Sofia, Bulgaria",
    focus: "Crypto lending, borrowing, and earn platform",
    logoText: "NX",
    logoBg: "#1F4BBE",
    logoFg: "#FFFFFF",
  },
  {
    name: "CertIK",
    slug: "certik",
    website: "https://certik.com",
    atsType: "greenhouse",
    atsSlug: "certik",
    ecosystems: ["evm", "solana"],
    stage: "Series B",
    hq: "New York, NY",
    focus: "Web3 security auditing platform and formal verification",
    logoText: "CK",
    logoBg: "#0052CC",
    logoFg: "#FFFFFF",
  },
  {
    name: "QuickNode",
    slug: "quicknode",
    website: "https://quicknode.com",
    atsType: "greenhouse",
    atsSlug: "quicknode",
    ecosystems: ["evm", "solana", "bitcoin"],
    stage: "Series B",
    hq: "Miami, FL",
    focus: "Multi-chain blockchain node infrastructure for developers",
    logoText: "QN",
    logoBg: "#4B44F6",
    logoFg: "#FFFFFF",
  },
  {
    name: "Ledger",
    slug: "ledger",
    website: "https://ledger.com",
    atsType: "greenhouse",
    atsSlug: "ledger",
    ecosystems: ["evm", "bitcoin"],
    stage: "Series C",
    hq: "Paris, France",
    focus: "The world's leading hardware wallet for self-custody",
    logoText: "LE",
    logoBg: "#000000",
    logoFg: "#FFFFFF",
  },
  {
    name: "OpenZeppelin",
    slug: "openzeppelin",
    website: "https://openzeppelin.com",
    atsType: "greenhouse",
    atsSlug: "openzeppelin",
    ecosystems: ["evm"],
    stage: "Private",
    hq: "Remote-first",
    focus: "Smart contract security library and audit firm",
    logoText: "OZ",
    logoBg: "#4E5EE4",
    logoFg: "#FFFFFF",
  },
  {
    name: "Bakkt",
    slug: "bakkt",
    website: "https://bakkt.com",
    atsType: "greenhouse",
    atsSlug: "bakkt",
    ecosystems: ["bitcoin", "evm"],
    stage: "Public (BKKT)",
    hq: "Alpharetta, GA",
    focus: "Regulated crypto platform for institutional and retail",
    logoText: "BK",
    logoBg: "#C4162A",
    logoFg: "#FFFFFF",
  },
  {
    name: "Gauntlet",
    slug: "gauntlet",
    website: "https://gauntlet.network",
    atsType: "greenhouse",
    atsSlug: "gauntlet-networks",
    ecosystems: ["evm"],
    stage: "Series B",
    hq: "New York, NY",
    focus: "Financial risk modeling and parameter optimization for DeFi",
    logoText: "GN",
    logoBg: "#0F172A",
    logoFg: "#F8FAFC",
  },
  {
    name: "Thirdweb",
    slug: "thirdweb",
    website: "https://thirdweb.com",
    atsType: "greenhouse",
    atsSlug: "thirdweb",
    ecosystems: ["evm", "solana"],
    stage: "Series A",
    hq: "Remote-first",
    focus: "Web3 developer toolkit for building onchain apps",
    logoText: "TW",
    logoBg: "#7C3AED",
    logoFg: "#FFFFFF",
  },
];

/* ── Lever companies ───────────────────────────────────────── */

const LEVER: CompanyEntry[] = [
  {
    name: "Uniswap Labs",
    slug: "uniswap-labs",
    website: "https://uniswap.org",
    atsType: "lever",
    atsSlug: "uniswaplabs",
    ecosystems: ["evm"],
    stage: "Private",
    hq: "New York, NY",
    focus: "Builders of the Uniswap protocol, the largest onchain DEX",
    logoText: "UL",
    logoBg: "#FF007A",
    logoFg: "#FFFFFF",
  },
  {
    name: "NEAR Protocol",
    slug: "near-protocol",
    website: "https://near.org",
    atsType: "lever",
    atsSlug: "near",
    ecosystems: ["evm"],
    stage: "Foundation",
    hq: "Remote-first",
    focus: "Layer-1 blockchain designed for user-owned AI and DeFi",
    logoText: "NR",
    logoBg: "#000000",
    logoFg: "#FFFFFF",
  },
  {
    name: "StarkWare",
    slug: "starkware",
    website: "https://starkware.co",
    atsType: "lever",
    atsSlug: "starkware",
    ecosystems: ["zk", "evm"],
    stage: "Series D",
    hq: "Tel Aviv, Israel",
    focus: "ZK-STARK scaling tech powering StarkNet",
    logoText: "SW",
    logoBg: "#29296E",
    logoFg: "#FFFFFF",
  },
  {
    name: "Matter Labs (zkSync)",
    slug: "matter-labs",
    website: "https://matter-labs.io",
    atsType: "lever",
    atsSlug: "matter-labs",
    ecosystems: ["zk", "evm"],
    stage: "Series C",
    hq: "Berlin, Germany",
    focus: "Core developers behind the zkSync Era ZK rollup",
    logoText: "ML",
    logoBg: "#1E69FF",
    logoFg: "#FFFFFF",
  },
  {
    name: "Ava Labs",
    slug: "ava-labs",
    website: "https://avax.network",
    atsType: "lever",
    atsSlug: "ava-labs",
    ecosystems: ["evm"],
    stage: "Series B",
    hq: "New York, NY",
    focus: "Company behind Avalanche blockchain ecosystem",
    logoText: "AV",
    logoBg: "#E84142",
    logoFg: "#FFFFFF",
  },
  {
    name: "Celestia Labs",
    slug: "celestia-labs",
    website: "https://celestia.org",
    atsType: "lever",
    atsSlug: "celestia",
    ecosystems: ["evm"],
    stage: "Series B",
    hq: "Remote-first",
    focus: "Modular blockchain network separating consensus from execution",
    logoText: "CL",
    logoBg: "#7B2BF9",
    logoFg: "#FFFFFF",
  },
  {
    name: "Aztec Network",
    slug: "aztec-network",
    website: "https://aztec.network",
    atsType: "lever",
    atsSlug: "aztecnetwork",
    ecosystems: ["zk", "evm"],
    stage: "Series B",
    hq: "London, UK",
    focus: "Privacy-first encrypted smart contract L2 using ZK proofs",
    logoText: "AZ",
    logoBg: "#1A1A2E",
    logoFg: "#FFFFFF",
  },
  {
    name: "Optimism Foundation",
    slug: "optimism-foundation",
    website: "https://optimism.io",
    atsType: "lever",
    atsSlug: "optimism-foundation",
    ecosystems: ["evm", "optimism"],
    stage: "Foundation",
    hq: "Remote-first",
    focus: "Stewards of the OP Stack and Optimism Collective",
    logoText: "OP",
    logoBg: "#FF0420",
    logoFg: "#FFFFFF",
  },
  {
    name: "Polygon Labs",
    slug: "polygon-labs",
    website: "https://polygon.technology",
    atsType: "lever",
    atsSlug: "polygon-labs",
    ecosystems: ["evm", "polygon", "zk"],
    stage: "Private",
    hq: "Remote-first",
    focus: "Building Polygon CDK and AggLayer for unified blockchain liquidity",
    logoText: "PL",
    logoBg: "#8247E5",
    logoFg: "#FFFFFF",
  },
  {
    name: "Mysten Labs (Sui)",
    slug: "mysten-labs",
    website: "https://mystenlabs.com",
    atsType: "lever",
    atsSlug: "mysten-labs",
    ecosystems: ["sui"],
    stage: "Series B",
    hq: "Palo Alto, CA",
    focus: "Core developers behind the Sui blockchain",
    logoText: "MY",
    logoBg: "#6FBCF0",
    logoFg: "#000000",
  },
  {
    name: "Aptos Labs",
    slug: "aptos-labs",
    website: "https://aptoslabs.com",
    atsType: "lever",
    atsSlug: "aptoslabs",
    ecosystems: ["evm"],
    stage: "Series B",
    hq: "Palo Alto, CA",
    focus: "Builders of the Aptos Layer-1 blockchain using Move",
    logoText: "AP",
    logoBg: "#03C4A1",
    logoFg: "#000000",
  },
  {
    name: "Dapper Labs",
    slug: "dapper-labs",
    website: "https://dapperlabs.com",
    atsType: "lever",
    atsSlug: "dapper-labs",
    ecosystems: ["evm"],
    stage: "Series E",
    hq: "Vancouver, Canada",
    focus: "Creators of Flow blockchain, NBA Top Shot, and NFL ALL DAY",
    logoText: "DL",
    logoBg: "#00EF8B",
    logoFg: "#000000",
  },
  {
    name: "The Graph",
    slug: "the-graph",
    website: "https://thegraph.com",
    atsType: "lever",
    atsSlug: "thegraph",
    ecosystems: ["evm", "solana"],
    stage: "Foundation",
    hq: "Remote-first",
    focus: "Decentralized indexing protocol for querying blockchain data",
    logoText: "TG",
    logoBg: "#5A2ADB",
    logoFg: "#FFFFFF",
  },
  {
    name: "0x Labs",
    slug: "0x-labs",
    website: "https://0x.org",
    atsType: "lever",
    atsSlug: "0xlabs",
    ecosystems: ["evm"],
    stage: "Private",
    hq: "San Francisco, CA",
    focus: "The open protocol for decentralized exchange infrastructure",
    logoText: "0X",
    logoBg: "#000000",
    logoFg: "#FFFFFF",
  },
  {
    name: "Dune Analytics",
    slug: "dune-analytics",
    website: "https://dune.com",
    atsType: "lever",
    atsSlug: "duneanalytics",
    ecosystems: ["evm", "solana"],
    stage: "Series B",
    hq: "Oslo, Norway",
    focus: "Blockchain data analytics platform for the community",
    logoText: "DA",
    logoBg: "#E8571A",
    logoFg: "#FFFFFF",
  },
  {
    name: "Balancer Labs",
    slug: "balancer-labs",
    website: "https://balancer.fi",
    atsType: "lever",
    atsSlug: "balancer-labs",
    ecosystems: ["evm"],
    stage: "Private",
    hq: "Remote-first",
    focus: "Programmable liquidity AMM protocol on Ethereum",
    logoText: "BL",
    logoBg: "#1E1E24",
    logoFg: "#FFFFFF",
  },
  {
    name: "Solana Labs",
    slug: "solana-labs",
    website: "https://solana.com",
    atsType: "lever",
    atsSlug: "solana-labs",
    ecosystems: ["solana"],
    stage: "Private",
    hq: "San Francisco, CA",
    focus: "Core development team behind the Solana blockchain",
    logoText: "SL",
    logoBg: "#9945FF",
    logoFg: "#FFFFFF",
  },
  {
    name: "Chainlink Labs",
    slug: "chainlink-labs",
    website: "https://chain.link",
    atsType: "lever",
    atsSlug: "chainlink-labs",
    ecosystems: ["evm", "solana"],
    stage: "Private",
    hq: "Remote-first",
    focus: "Decentralized oracle network connecting blockchains to real-world data",
    logoText: "CL",
    logoBg: "#375BD2",
    logoFg: "#FFFFFF",
  },
  {
    name: "Paradigm",
    slug: "paradigm",
    website: "https://paradigm.xyz",
    atsType: "lever",
    atsSlug: "paradigm",
    ecosystems: ["evm"],
    stage: "VC Firm",
    hq: "San Francisco, CA",
    focus: "Crypto-focused investment firm building foundational research and tools",
    logoText: "PA",
    logoBg: "#000000",
    logoFg: "#FFFFFF",
  },
  {
    name: "a16z Crypto",
    slug: "a16z-crypto",
    website: "https://a16zcrypto.com",
    atsType: "lever",
    atsSlug: "a16zcrypto",
    ecosystems: ["evm", "solana"],
    stage: "VC Firm",
    hq: "San Francisco, CA",
    focus: "Andreessen Horowitz's crypto venture and research arm",
    logoText: "a6",
    logoBg: "#0D0D0D",
    logoFg: "#FFFFFF",
  },
  {
    name: "Multicoin Capital",
    slug: "multicoin-capital",
    website: "https://multicoin.capital",
    atsType: "lever",
    atsSlug: "multicoin-capital",
    ecosystems: ["solana", "evm"],
    stage: "VC Firm",
    hq: "Austin, TX",
    focus: "Thesis-driven crypto fund backing long-term infrastructure",
    logoText: "MC",
    logoBg: "#1A1A1A",
    logoFg: "#FFFFFF",
  },
  {
    name: "Sei Labs",
    slug: "sei-labs",
    website: "https://sei.io",
    atsType: "lever",
    atsSlug: "sei-labs",
    ecosystems: ["evm", "cosmos"],
    stage: "Series B",
    hq: "San Francisco, CA",
    focus: "Builders of Sei, the fastest EVM L1 chain",
    logoText: "SE",
    logoBg: "#9D1E4C",
    logoFg: "#FFFFFF",
  },
  {
    name: "Scroll",
    slug: "scroll",
    website: "https://scroll.io",
    atsType: "lever",
    atsSlug: "scroll",
    ecosystems: ["zk", "evm"],
    stage: "Series A",
    hq: "Remote-first",
    focus: "zkEVM rollup built for Ethereum scalability",
    logoText: "SC",
    logoBg: "#FFDBB0",
    logoFg: "#000000",
  },
  {
    name: "Fuel Labs",
    slug: "fuel-labs",
    website: "https://fuel.network",
    atsType: "lever",
    atsSlug: "fuellabs",
    ecosystems: ["evm"],
    stage: "Series A",
    hq: "Remote-first",
    focus: "Modular execution layer with the FuelVM and Sway language",
    logoText: "FL",
    logoBg: "#00F58C",
    logoFg: "#000000",
  },
  {
    name: "Osmosis Labs",
    slug: "osmosis-labs",
    website: "https://osmosis.zone",
    atsType: "lever",
    atsSlug: "osmosis-labs",
    ecosystems: ["cosmos"],
    stage: "Private",
    hq: "Remote-first",
    focus: "Leading DEX for the Cosmos IBC ecosystem",
    logoText: "OS",
    logoBg: "#6B21A8",
    logoFg: "#FFFFFF",
  },
  {
    name: "Informal Systems",
    slug: "informal-systems",
    website: "https://informal.systems",
    atsType: "lever",
    atsSlug: "informal-systems",
    ecosystems: ["cosmos"],
    stage: "Private",
    hq: "Toronto, Canada",
    focus: "Formal verification and Cosmos IBC protocol development",
    logoText: "IS",
    logoBg: "#2D3748",
    logoFg: "#FFFFFF",
  },
  {
    name: "Parity Technologies",
    slug: "parity-technologies",
    website: "https://parity.io",
    atsType: "lever",
    atsSlug: "parity-technologies",
    ecosystems: ["evm"],
    stage: "Private",
    hq: "Berlin, Germany",
    focus: "Core developers of Polkadot and Substrate blockchain framework",
    logoText: "PT",
    logoBg: "#E6007A",
    logoFg: "#FFFFFF",
  },
  {
    name: "Morpho Labs",
    slug: "morpho-labs",
    website: "https://morpho.org",
    atsType: "lever",
    atsSlug: "morpho-labs",
    ecosystems: ["evm", "base"],
    stage: "Series A",
    hq: "Paris, France",
    focus: "Optimized lending protocol built on Aave and Compound",
    logoText: "MO",
    logoBg: "#2470FF",
    logoFg: "#FFFFFF",
  },
  {
    name: "Succinct Labs",
    slug: "succinct-labs",
    website: "https://succinct.xyz",
    atsType: "lever",
    atsSlug: "succinctlabs",
    ecosystems: ["zk", "evm"],
    stage: "Series A",
    hq: "Remote-first",
    focus: "ZK coprocessor enabling verifiable on-chain computations",
    logoText: "SU",
    logoBg: "#FF6E00",
    logoFg: "#FFFFFF",
  },
  {
    name: "Babylon Chain",
    slug: "babylon-chain",
    website: "https://babylonchain.io",
    atsType: "lever",
    atsSlug: "babylonchain",
    ecosystems: ["bitcoin", "cosmos"],
    stage: "Series A",
    hq: "Remote-first",
    focus: "Bitcoin staking protocol bringing BTC security to Cosmos chains",
    logoText: "BB",
    logoBg: "#FF6B00",
    logoFg: "#FFFFFF",
  },
  {
    name: "EigenLayer (Eigen Labs)",
    slug: "eigen-labs",
    website: "https://eigenlayer.xyz",
    atsType: "lever",
    atsSlug: "eigen-labs",
    ecosystems: ["evm"],
    stage: "Series A",
    hq: "Seattle, WA",
    focus: "Restaking protocol extending Ethereum crypto-economic security",
    logoText: "EL",
    logoBg: "#1A1A1A",
    logoFg: "#FFFFFF",
  },
  {
    name: "Ethena Labs",
    slug: "ethena-labs",
    website: "https://ethena.fi",
    atsType: "lever",
    atsSlug: "ethena-labs",
    ecosystems: ["evm"],
    stage: "Series A",
    hq: "Remote-first",
    focus: "Synthetic dollar protocol (USDe) built on Ethereum",
    logoText: "EN",
    logoBg: "#7F4FC4",
    logoFg: "#FFFFFF",
  },
  {
    name: "Zora",
    slug: "zora",
    website: "https://zora.co",
    atsType: "lever",
    atsSlug: "zora",
    ecosystems: ["evm", "base"],
    stage: "Series A",
    hq: "Remote-first",
    focus: "NFT protocol and L2 network for creators and collectors",
    logoText: "ZO",
    logoBg: "#000000",
    logoFg: "#FFFFFF",
  },
  {
    name: "Ether.fi",
    slug: "ether-fi",
    website: "https://ether.fi",
    atsType: "lever",
    atsSlug: "ether-fi",
    ecosystems: ["evm"],
    stage: "Series A",
    hq: "Remote-first",
    focus: "Decentralized, non-custodial Ethereum liquid restaking protocol",
    logoText: "EF",
    logoBg: "#1C1C1C",
    logoFg: "#FFFFFF",
  },
  {
    name: "Aave",
    slug: "aave",
    website: "https://aave.com",
    atsType: "lever",
    atsSlug: "aave",
    ecosystems: ["evm"],
    stage: "Foundation",
    hq: "London, UK",
    focus: "Leading decentralized lending and borrowing protocol",
    logoText: "AA",
    logoBg: "#B6509E",
    logoFg: "#FFFFFF",
  },
  {
    name: "Compound Labs",
    slug: "compound-labs",
    website: "https://compound.finance",
    atsType: "lever",
    atsSlug: "compound-finance",
    ecosystems: ["evm"],
    stage: "Private",
    hq: "San Francisco, CA",
    focus: "Decentralized lending protocol pioneering DeFi yield",
    logoText: "CO",
    logoBg: "#00D395",
    logoFg: "#000000",
  },
  {
    name: "Helium Foundation",
    slug: "helium-foundation",
    website: "https://helium.com",
    atsType: "lever",
    atsSlug: "helium",
    ecosystems: ["solana"],
    stage: "Foundation",
    hq: "Remote-first",
    focus: "Decentralized wireless network for IoT and 5G on Solana",
    logoText: "HE",
    logoBg: "#474DFF",
    logoFg: "#FFFFFF",
  },
  {
    name: "Livepeer",
    slug: "livepeer",
    website: "https://livepeer.org",
    atsType: "lever",
    atsSlug: "livepeer",
    ecosystems: ["evm"],
    stage: "Private",
    hq: "New York, NY",
    focus: "Decentralized video transcoding and streaming infrastructure",
    logoText: "LP",
    logoBg: "#00EB88",
    logoFg: "#000000",
  },
  {
    name: "Sky (MakerDAO)",
    slug: "sky-makerdao",
    website: "https://sky.money",
    atsType: "lever",
    atsSlug: "makerdao",
    ecosystems: ["evm"],
    stage: "DAO",
    hq: "Remote-first",
    focus: "Builders of DAI stablecoin and Sky savings protocol",
    logoText: "SK",
    logoBg: "#1AAB9B",
    logoFg: "#FFFFFF",
  },
  {
    name: "Safe (Gnosis Safe)",
    slug: "safe-global",
    website: "https://safe.global",
    atsType: "lever",
    atsSlug: "safe-global",
    ecosystems: ["evm"],
    stage: "Private",
    hq: "Berlin, Germany",
    focus: "Smart account infrastructure for multi-sig and account abstraction",
    logoText: "SG",
    logoBg: "#12FF80",
    logoFg: "#000000",
  },
  {
    name: "Lido Finance",
    slug: "lido-finance",
    website: "https://lido.fi",
    atsType: "lever",
    atsSlug: "lidofinance",
    ecosystems: ["evm"],
    stage: "DAO",
    hq: "Remote-first",
    focus: "Liquid staking protocol with stETH, the largest DeFi asset",
    logoText: "LI",
    logoBg: "#00A3FF",
    logoFg: "#FFFFFF",
  },
  {
    name: "Penumbra",
    slug: "penumbra",
    website: "https://penumbra.zone",
    atsType: "lever",
    atsSlug: "penumbra",
    ecosystems: ["zk", "cosmos"],
    stage: "Private",
    hq: "Remote-first",
    focus: "Fully shielded DEX and staking built on ZK proofs",
    logoText: "PE",
    logoBg: "#8B5CF6",
    logoFg: "#FFFFFF",
  },
  {
    name: "Evmos",
    slug: "evmos",
    website: "https://evmos.org",
    atsType: "lever",
    atsSlug: "evmos-org",
    ecosystems: ["evm", "cosmos"],
    stage: "Foundation",
    hq: "Remote-first",
    focus: "EVM-compatible chain bringing Ethereum apps to Cosmos",
    logoText: "EV",
    logoBg: "#ED4E33",
    logoFg: "#FFFFFF",
  },
  {
    name: "Gelato Network",
    slug: "gelato-network",
    website: "https://gelato.network",
    atsType: "lever",
    atsSlug: "gelato-network",
    ecosystems: ["evm"],
    stage: "Private",
    hq: "Zug, Switzerland",
    focus: "Web3 cloud for smart contract automation and rollup infrastructure",
    logoText: "GE",
    logoBg: "#FF5B79",
    logoFg: "#FFFFFF",
  },
  {
    name: "Gnosis",
    slug: "gnosis",
    website: "https://gnosis.io",
    atsType: "lever",
    atsSlug: "gnosis",
    ecosystems: ["evm"],
    stage: "DAO",
    hq: "Berlin, Germany",
    focus: "DAO and prediction market ecosystem on Gnosis Chain",
    logoText: "GN",
    logoBg: "#00857A",
    logoFg: "#FFFFFF",
  },
  {
    name: "Synthetix",
    slug: "synthetix",
    website: "https://synthetix.io",
    atsType: "lever",
    atsSlug: "synthetix",
    ecosystems: ["evm", "optimism"],
    stage: "DAO",
    hq: "Remote-first",
    focus: "Decentralized synthetic assets and liquidity for derivatives",
    logoText: "SY",
    logoBg: "#08021E",
    logoFg: "#FFFFFF",
  },
];

/* ── Ashby companies (confirmed working 2026-05-27) ───────── */

const ASHBY: CompanyEntry[] = [
  {
    name: "Uniswap Labs",
    slug: "uniswap-labs",
    website: "https://uniswap.org",
    atsType: "ashby",
    atsSlug: "uniswap",
    ecosystems: ["evm"],
    stage: "Private",
    hq: "New York, NY",
    focus: "Builders of the Uniswap protocol, the largest onchain DEX",
    logoText: "UL",
    logoBg: "#FF007A",
    logoFg: "#FFFFFF",
  },
  {
    name: "Matter Labs (zkSync)",
    slug: "matter-labs",
    website: "https://matter-labs.io",
    atsType: "ashby",
    atsSlug: "matter-labs",
    ecosystems: ["zk", "evm"],
    stage: "Series C",
    hq: "Berlin, Germany",
    focus: "Core developers behind the zkSync Era ZK rollup",
    logoText: "ML",
    logoBg: "#1E69FF",
    logoFg: "#FFFFFF",
  },
  {
    name: "Ava Labs",
    slug: "ava-labs",
    website: "https://avax.network",
    atsType: "ashby",
    atsSlug: "ava-labs",
    ecosystems: ["evm"],
    stage: "Series B",
    hq: "New York, NY",
    focus: "Company behind Avalanche blockchain ecosystem",
    logoText: "AV",
    logoBg: "#E84142",
    logoFg: "#FFFFFF",
  },
  {
    name: "Paradigm",
    slug: "paradigm",
    website: "https://paradigm.xyz",
    atsType: "ashby",
    atsSlug: "paradigm",
    ecosystems: ["evm"],
    stage: "VC Firm",
    hq: "San Francisco, CA",
    focus: "Crypto-focused investment firm building foundational research and tools",
    logoText: "PA",
    logoBg: "#000000",
    logoFg: "#FFFFFF",
  },
  {
    name: "a16z Crypto",
    slug: "a16z-crypto",
    website: "https://a16zcrypto.com",
    atsType: "ashby",
    atsSlug: "a16z-crypto",
    ecosystems: ["evm", "solana"],
    stage: "VC Firm",
    hq: "San Francisco, CA",
    focus: "Andreessen Horowitz's crypto venture and research arm",
    logoText: "a6",
    logoBg: "#0D0D0D",
    logoFg: "#FFFFFF",
  },
  {
    name: "Succinct Labs",
    slug: "succinct-labs",
    website: "https://succinct.xyz",
    atsType: "ashby",
    atsSlug: "succinct",
    ecosystems: ["zk", "evm"],
    stage: "Series A",
    hq: "Remote-first",
    focus: "ZK coprocessor enabling verifiable on-chain computations",
    logoText: "SU",
    logoBg: "#FF6E00",
    logoFg: "#FFFFFF",
  },
  {
    name: "Compound Labs",
    slug: "compound-labs",
    website: "https://compound.finance",
    atsType: "ashby",
    atsSlug: "compound",
    ecosystems: ["evm"],
    stage: "Private",
    hq: "San Francisco, CA",
    focus: "Decentralized lending protocol pioneering DeFi yield",
    logoText: "CO",
    logoBg: "#00D395",
    logoFg: "#000000",
  },
  {
    name: "Safe (Gnosis Safe)",
    slug: "safe-global",
    website: "https://safe.global",
    atsType: "ashby",
    atsSlug: "safe",
    ecosystems: ["evm"],
    stage: "Private",
    hq: "Berlin, Germany",
    focus: "Smart account infrastructure for multi-sig and account abstraction",
    logoText: "SG",
    logoBg: "#12FF80",
    logoFg: "#000000",
  },
  {
    name: "Morpho Labs",
    slug: "morpho-labs",
    website: "https://morpho.org",
    atsType: "ashby",
    atsSlug: "morpho",
    ecosystems: ["evm", "base"],
    stage: "Series A",
    hq: "Paris, France",
    focus: "Optimized lending protocol built on Aave and Compound",
    logoText: "MO",
    logoBg: "#2470FF",
    logoFg: "#FFFFFF",
  },
  {
    name: "Kraken",
    slug: "kraken",
    website: "https://kraken.com",
    atsType: "ashby",
    atsSlug: "kraken",
    ecosystems: ["evm", "bitcoin"],
    stage: "Private",
    hq: "Remote-first",
    focus: "Global crypto exchange with deep liquidity",
    logoText: "KR",
    logoBg: "#5741D9",
    logoFg: "#FFFFFF",
  },
  {
    name: "Dapper Labs",
    slug: "dapper-labs",
    website: "https://dapperlabs.com",
    atsType: "ashby",
    atsSlug: "dapper",
    ecosystems: ["evm"],
    stage: "Series E",
    hq: "Vancouver, Canada",
    focus: "Creators of Flow blockchain, NBA Top Shot, and NFL ALL DAY",
    logoText: "DL",
    logoBg: "#00EF8B",
    logoFg: "#000000",
  },
  {
    name: "Dune Analytics",
    slug: "dune-analytics",
    website: "https://dune.com",
    atsType: "ashby",
    atsSlug: "dune",
    ecosystems: ["evm", "solana"],
    stage: "Series B",
    hq: "Oslo, Norway",
    focus: "Blockchain data analytics platform for the community",
    logoText: "DA",
    logoBg: "#E8571A",
    logoFg: "#FFFFFF",
  },
  {
    name: "EigenLayer (Eigen Labs)",
    slug: "eigen-labs",
    website: "https://eigenlayer.xyz",
    atsType: "ashby",
    atsSlug: "eigen-labs",
    ecosystems: ["evm"],
    stage: "Series A",
    hq: "Seattle, WA",
    focus: "Restaking protocol extending Ethereum crypto-economic security",
    logoText: "EL",
    logoBg: "#1A1A1A",
    logoFg: "#FFFFFF",
  },
  {
    name: "Parity Technologies",
    slug: "parity-technologies",
    website: "https://parity.io",
    atsType: "ashby",
    atsSlug: "parity",
    ecosystems: ["evm"],
    stage: "Private",
    hq: "Berlin, Germany",
    focus: "Core developers of Polkadot and Substrate blockchain framework",
    logoText: "PT",
    logoBg: "#E6007A",
    logoFg: "#FFFFFF",
  },
  {
    name: "Alchemy",
    slug: "alchemy",
    website: "https://alchemy.com",
    atsType: "ashby",
    atsSlug: "alchemy",
    ecosystems: ["evm", "solana"],
    stage: "Series C",
    hq: "San Francisco, CA",
    focus: "The leading web3 developer platform and node infrastructure",
    logoText: "AL",
    logoBg: "#363FF9",
    logoFg: "#FFFFFF",
  },
  {
    name: "QuickNode",
    slug: "quicknode",
    website: "https://quicknode.com",
    atsType: "ashby",
    atsSlug: "quicknode",
    ecosystems: ["evm", "solana", "bitcoin"],
    stage: "Series B",
    hq: "Miami, FL",
    focus: "Multi-chain blockchain node infrastructure for developers",
    logoText: "QN",
    logoBg: "#4B44F6",
    logoFg: "#FFFFFF",
  },
  {
    name: "Aztec Network",
    slug: "aztec-network",
    website: "https://aztec.network",
    atsType: "ashby",
    atsSlug: "aztec-labs",
    ecosystems: ["zk", "evm"],
    stage: "Series B",
    hq: "London, UK",
    focus: "Privacy-first encrypted smart contract L2 using ZK proofs",
    logoText: "AZ",
    logoBg: "#1A1A2E",
    logoFg: "#FFFFFF",
  },
  {
    name: "Paxos",
    slug: "paxos",
    website: "https://paxos.com",
    atsType: "ashby",
    atsSlug: "paxos",
    ecosystems: ["evm"],
    stage: "Series D",
    hq: "New York, NY",
    focus: "Regulated blockchain infrastructure for tokenized assets",
    logoText: "PX",
    logoBg: "#00C805",
    logoFg: "#000000",
  },
  {
    name: "Ledger",
    slug: "ledger",
    website: "https://ledger.com",
    atsType: "ashby",
    atsSlug: "ledger",
    ecosystems: ["evm", "bitcoin"],
    stage: "Series C",
    hq: "Paris, France",
    focus: "The world's leading hardware wallet for self-custody",
    logoText: "LE",
    logoBg: "#000000",
    logoFg: "#FFFFFF",
  },
  {
    name: "OpenSea",
    slug: "opensea",
    website: "https://opensea.io",
    atsType: "ashby",
    atsSlug: "opensea",
    ecosystems: ["evm", "solana"],
    stage: "Series C",
    hq: "New York, NY",
    focus: "The world's largest NFT marketplace",
    logoText: "OS",
    logoBg: "#2081E2",
    logoFg: "#FFFFFF",
  },
  {
    name: "Polygon Labs",
    slug: "polygon-labs",
    website: "https://polygon.technology",
    atsType: "ashby",
    atsSlug: "polygon-labs",
    ecosystems: ["evm", "polygon", "zk"],
    stage: "Private",
    hq: "Remote-first",
    focus: "Building Polygon CDK and AggLayer for unified blockchain liquidity",
    logoText: "PL",
    logoBg: "#8247E5",
    logoFg: "#FFFFFF",
  },
  {
    name: "Injective Labs",
    slug: "injective-labs",
    website: "https://injective.com",
    atsType: "ashby",
    atsSlug: "injective-labs",
    ecosystems: ["evm", "cosmos"],
    stage: "Series B",
    hq: "Remote-first",
    focus: "Decentralized exchange and DeFi protocol on Cosmos",
    logoText: "IN",
    logoBg: "#0082FA",
    logoFg: "#FFFFFF",
  },
  {
    name: "Helius",
    slug: "helius",
    website: "https://helius.dev",
    atsType: "ashby",
    atsSlug: "helius",
    ecosystems: ["solana"],
    stage: "Series A",
    hq: "Remote-first",
    focus: "Leading Solana RPC and developer infrastructure provider",
    logoText: "HE",
    logoBg: "#FF7B00",
    logoFg: "#FFFFFF",
  },
  {
    name: "Blockdaemon",
    slug: "blockdaemon",
    website: "https://blockdaemon.com",
    atsType: "ashby",
    atsSlug: "blockdaemon",
    ecosystems: ["evm", "bitcoin", "solana"],
    stage: "Series C",
    hq: "New York, NY",
    focus: "Enterprise blockchain node infrastructure and staking platform",
    logoText: "BD",
    logoBg: "#1F2937",
    logoFg: "#FFFFFF",
  },
];

/* ── Discovered 2026-06-03 ─────────────────────────────────────
   Sourced via a low-cost LLM web-search fan-out, then gated
   DETERMINISTICALLY: each ATS slug below was confirmed live against the
   public Greenhouse/Lever/Ashby API and shown to return real ENGINEERING
   roles. Candidates that 404'd, were empty, had no eng roles, or were
   non-crypto false positives (e.g. socket.dev, render.com) were dropped.
   Apply URLs come straight from the official ATS — no scraped links. */
const DISCOVERED_2026_06: CompanyEntry[] = [
  // ZK / cryptography / identity
  {
    name: "Nexus",
    slug: "nexus",
    website: "https://nexus.xyz",
    atsType: "ashby",
    atsSlug: "nexus.xyz",
    ecosystems: ["zk", "ai"],
    focus: "zkVM Layer 1 for verifiable compute",
    logoText: "NX",
    logoBg: "#6E56CF",
    logoFg: "#FFFFFF",
  },
  {
    name: "Axiom",
    slug: "axiom",
    website: "https://axiom.xyz",
    atsType: "ashby",
    atsSlug: "axiom",
    ecosystems: ["zk", "evm"],
    focus: "ZK coprocessor for Ethereum",
    logoText: "AX",
    logoBg: "#4F46E5",
    logoFg: "#FFFFFF",
  },
  {
    name: "NEBRA",
    slug: "nebra",
    website: "https://nebra.com",
    atsType: "lever",
    atsSlug: "nebra-labs",
    ecosystems: ["zk", "evm"],
    focus: "ZK proof aggregation infrastructure",
    logoText: "NB",
    logoBg: "#111827",
    logoFg: "#FFFFFF",
  },
  {
    name: "SpruceID",
    slug: "spruceid",
    website: "https://spruceid.com",
    atsType: "lever",
    atsSlug: "sprucesystems",
    ecosystems: ["evm", "zk"],
    focus: "Decentralized identity and verifiable credentials",
    logoText: "SP",
    logoBg: "#2563EB",
    logoFg: "#FFFFFF",
  },
  {
    name: "Sigma Prime",
    slug: "sigma-prime",
    website: "https://sigmaprime.io",
    atsType: "ashby",
    atsSlug: "sigp",
    ecosystems: ["evm"],
    focus: "Ethereum Lighthouse client and protocol security",
    logoText: "SG",
    logoBg: "#1F2937",
    logoFg: "#FFFFFF",
  },
  // Solana ecosystem
  {
    name: "Jito",
    slug: "jito",
    website: "https://jito.network",
    atsType: "lever",
    atsSlug: "jito.wtf",
    ecosystems: ["solana"],
    focus: "Solana MEV and liquid staking infrastructure",
    logoText: "JT",
    logoBg: "#14B8A6",
    logoFg: "#0B1B17",
  },
  {
    name: "Phantom",
    slug: "phantom",
    website: "https://phantom.com",
    atsType: "ashby",
    atsSlug: "phantom",
    ecosystems: ["solana", "evm", "bitcoin"],
    focus: "Leading multichain self-custody crypto wallet",
    logoText: "PH",
    logoBg: "#AB9FF2",
    logoFg: "#2A2A3C",
  },
  {
    name: "Syndica",
    slug: "syndica",
    website: "https://syndica.io",
    atsType: "ashby",
    atsSlug: "syndica",
    ecosystems: ["solana"],
    focus: "Solana RPC and developer infrastructure",
    logoText: "SY",
    logoBg: "#0EA5E9",
    logoFg: "#FFFFFF",
  },
  {
    name: "Wormhole",
    slug: "wormhole",
    website: "https://wormhole.com",
    atsType: "ashby",
    atsSlug: "wormholelabs",
    ecosystems: ["evm", "solana"],
    focus: "Cross-chain messaging and interoperability",
    logoText: "WH",
    logoBg: "#1E1B3A",
    logoFg: "#FFFFFF",
  },
  {
    name: "Squads",
    slug: "squads",
    website: "https://squads.so",
    atsType: "ashby",
    atsSlug: "squads",
    ecosystems: ["solana"],
    focus: "Solana multisig and smart-account infrastructure",
    logoText: "SQ",
    logoBg: "#111111",
    logoFg: "#FFFFFF",
  },
  // Staking / restaking / infra
  {
    name: "P2P.org",
    slug: "p2p-org",
    website: "https://p2p.org",
    atsType: "ashby",
    atsSlug: "p2p.org",
    ecosystems: ["evm", "solana", "cosmos"],
    focus: "Institutional staking and restaking infrastructure",
    logoText: "P2",
    logoBg: "#FF6B35",
    logoFg: "#FFFFFF",
  },
  {
    name: "SSV Labs",
    slug: "ssv-labs",
    website: "https://ssvlabs.io",
    atsType: "greenhouse",
    atsSlug: "bloxstaking",
    ecosystems: ["evm"],
    focus: "Distributed validator technology (DVT) for Ethereum",
    logoText: "SS",
    logoBg: "#1BA5F8",
    logoFg: "#FFFFFF",
  },
  // DeFi / RWA / interoperability
  {
    name: "CoW DAO",
    slug: "cow-dao",
    website: "https://cow.fi",
    atsType: "ashby",
    atsSlug: "cow-dao",
    ecosystems: ["evm"],
    focus: "Intent-based DEX and MEV protection (CoW Protocol)",
    logoText: "CW",
    logoBg: "#052B65",
    logoFg: "#FFFFFF",
  },
  {
    name: "LayerZero",
    slug: "layerzero",
    website: "https://layerzero.network",
    atsType: "greenhouse",
    atsSlug: "layerzerolabs",
    ecosystems: ["evm", "solana"],
    focus: "Omnichain interoperability protocol",
    logoText: "LZ",
    logoBg: "#000000",
    logoFg: "#FFFFFF",
  },
  {
    name: "Superstate",
    slug: "superstate",
    website: "https://superstate.xyz",
    atsType: "lever",
    atsSlug: "superstate",
    ecosystems: ["evm"],
    focus: "Tokenized real-world-asset funds",
    logoText: "SU",
    logoBg: "#0F172A",
    logoFg: "#FFFFFF",
  },
  {
    name: "Goldsky",
    slug: "goldsky",
    website: "https://goldsky.com",
    atsType: "ashby",
    atsSlug: "goldsky",
    ecosystems: ["evm"],
    focus: "Crypto data indexing and real-time streaming",
    logoText: "GS",
    logoBg: "#F5A623",
    logoFg: "#1A1A1A",
  },
  // AI x crypto / high-performance L1
  {
    name: "Ritual",
    slug: "ritual",
    website: "https://ritual.net",
    atsType: "greenhouse",
    atsSlug: "ritual",
    ecosystems: ["ai", "evm"],
    focus: "Sovereign execution layer for AI",
    logoText: "RT",
    logoBg: "#DC2626",
    logoFg: "#FFFFFF",
  },
  {
    name: "Monad",
    slug: "monad",
    website: "https://monad.xyz",
    atsType: "ashby",
    atsSlug: "monad.foundation",
    ecosystems: ["evm"],
    focus: "High-performance parallel EVM Layer 1",
    logoText: "MO",
    logoBg: "#836EF9",
    logoFg: "#FFFFFF",
  },
  {
    name: "Hyperbolic",
    slug: "hyperbolic",
    website: "https://hyperbolic.xyz",
    atsType: "ashby",
    atsSlug: "hyperbolic",
    ecosystems: ["ai"],
    focus: "Decentralized GPU and AI compute network",
    logoText: "HY",
    logoBg: "#16A34A",
    logoFg: "#FFFFFF",
  },
];

/* ── Workable companies ────────────────────────────────────
 * Workable public widget API:
 *   GET https://apply.workable.com/api/v1/widget/accounts/{atsSlug}?details=true
 * Most large crypto firms live on Greenhouse/Lever/Ashby; Workable skews to
 * smaller / EU-based teams. Slugs verified to return an account; 404s and
 * 0-job accounts are silently skipped at ingest time. */

const WORKABLE: CompanyEntry[] = [
  {
    name: "1inch",
    slug: "1inch",
    website: "https://1inch.io",
    atsType: "workable",
    atsSlug: "1inch",
    ecosystems: ["evm"],
    focus: "DEX aggregator and DeFi infrastructure",
    logoText: "1I",
    logoBg: "#1B314F",
    logoFg: "#FFFFFF",
  },
];

export const COMPANY_REGISTRY: CompanyEntry[] = [
  ...GREENHOUSE,
  ...LEVER,
  ...ASHBY,
  ...DISCOVERED_2026_06,
  ...WORKABLE,
];

/** Resolve registry entry by ATS type + slug (used during dedup). */
export function findCompanyByATS(
  atsType: ATSType,
  atsSlug: string,
): CompanyEntry | undefined {
  return COMPANY_REGISTRY.find(
    (c) => c.atsType === atsType && c.atsSlug === atsSlug,
  );
}
